-- generated by Digital. Don't modify this file!
-- Any changes will be lost if this file is regenerated.

LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

entity main is
  port (
    a_1: in std_logic;
    b_1: in std_logic;
    s_1: out std_logic;
    t_1: out std_logic;
    r_1: out std_logic;
    u_1: out std_logic);
end main;

architecture Behavioral of main is
  signal s_1_temp: std_logic;
begin
  s_1_temp <= (a_1 XOR b_1);
  r_1 <= (b_1 AND a_1);
  u_1 <= (b_1 OR a_1);
  t_1 <= NOT s_1_temp;
  s_1 <= s_1_temp;
end Behavioral;
